name: Create Release Branch

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., 1.0.0)'
        required: true

jobs:
  create-release-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create Release Branch
        run: |
          git checkout develop
          git checkout -b release/v${{ github.event.inputs.version }}
          # package.json 버전 업데이트
          npm version ${{ github.event.inputs.version }} --no-git-tag-version
          git add package.json
          git commit -m "chore: bump version to v${{ github.event.inputs.version }}"
          git push origin release/v${{ github.event.inputs.version }}
